config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'pages#home'

  # Static Pages
  get '/about',   to: 'pages#about',   as: :about
  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/contact', to: 'pages#contact', as: :contact
  get '/features', to: 'pages#features', as: :features

  get '/dashboard', to: 'dashboards#index', as: :dashboard

  # Organisations
  get '/organisations/new',            to: 'organisations#new',       as: :new_organisation
  get '/organisations/:ref',           to: 'organisations#show',      as: :organisation
  get '/organisations/:ref/edit',      to: 'organisations#edit',      as: :edit_organisation
  get '/organisations',                to: 'organisations#index',     as: :organisations
  match '/organisations',              to: 'organisations#create',    as: :create_organisation, via: :post
  match '/organisations/:ref',         to: 'organisations#destroy',   as: :delete_organisation, via: :delete
  match '/organisations/:ref',         to: 'organisations#update',                              via: :patch

  # Users
  get '/users',          to: 'users#index',   as: :users
  get '/users/:id/edit', to: 'users#edit',    as: :edit_user
  get '/users/:id',      to: 'users#show',    as: :user
  match '/users/:id',    to: 'users#destroy', as: :delete_user, via: :delete
  match '/users/:id',    to: 'users#update',                    via: :patch

  # Student Import
  get '/students/add',      to: 'student_imports#new', as: :add_students
  get '/students/add',      to: 'student_imports#new', as: :student_imports
  get '/students/add',      to: 'student_imports#new', as: :new_student_import
  match '/students/add',    to: 'student_imports#create', via: :post

  match '/students/create', to: 'student_imports#create_student', as: :create_individual_student, via: :post

  # Courses
  resources :courses

  # Tracks
  get '/courses/:id/tracks',     to: 'tracks#index',       as: :tracks
  get '/courses/:id/tracks/new', to: 'tracks#new',         as: :new_track
  get '/tracks/:id',             to: 'tracks#show',        as: :track
  get '/tracks/:id/edit',        to: 'tracks#edit',        as: :edit_track
  get '/tracks/:id/edit-order',  to: 'tracks#edit_order',  as: :edit_track_order
  match '/courses/:id/tracks',   to: 'tracks#create',                 via: :post
  match '/update-lesson-order',  to: 'tracks#update_lesson_order', as: :update_lesson_order, via: :post

  # Code Lessons
  get '/tracks/:id/code-lessons/new',                          to: 'code_lessons#new',       as: :new_code_lesson
  get '/tracks/:id/code-lessons',                              to: 'code_lessons#index',     as: :code_lessons
  get '/code-lessons/:id',                                     to: 'code_lessons#show',      as: :code_lesson
  get '/code-lessons/:id/edit',                                to: 'code_lessons#edit',      as: :edit_code_lesson
  get '/code-lessons/:id/stats',                               to: 'code_lessons#stats',     as: :code_lesson_stats
  get '/code-lessons/:code_lesson_id/submission/:progress_id', to: 'code_lessons#submission', as: :code_lesson_submission
  match '/code-lessons/:id',                                   to: 'code_lessons#destroy',   as: :delete_code_lesson, via: :delete
  match '/code-lessons/:id',                                   to: 'code_lessons#update',                             via: :patch
  match '/tracks/:id/code-lessons',                            to: 'code_lessons#create',    as: :create_code_lesson, via: :post
  match '/evaluate',                                           to: 'code_lessons#evaluate',  as: :new_submission,     via: :post
  match '/run-code',                                           to: 'code_lessons#run_code',  as: :new_run_code,       via: :post
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :course
  has_many :code_lessons, dependent: :destroy

  validates :name,        presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 250 }

  def to_param
    [id, name.parameterize].join('-')
  end

  def items
    items = CodeLesson.where(track_id: self.id) +
      []

    items.sort_by! { |item| item.order }
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_teacher!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @track = Track.new
  end

  def create
    @course = Course.find params[:id]
    @track = @course.tracks.build track_params
    if @track.save
      flash[:success] = 'Track saved'
      redirect_to track_path @track
    else
      render :new
    end
  end

  def edit
    @track = Track.find params[:id]
  end

  def update
  end

  def show
    @track = Track.find params[:id]
    @code_lesson = CodeLesson.new
  end

  def index
    @tracks = Track.all.where organisation_id: current_org.id
  end

  def destroy
    @track = Track.find params[:id]
  end

  def edit_order
    @track = Track.find params[:id]
    @items = @track.items.sort_by! { |item| item.order }
  end

  def update_lesson_order
    @track = Track.find params[:track][:track_id]
    params[:track][:items].each do |i|
      # find_lesson_from_class_id found in ApplicationHelper
      item = find_lesson_from_class_id(i[1][:id], i[1][:type])
      item.update_attributes(order: i[1][:order])
      item.save
    end

    flash[:success] = 'Order changed'
    redirect_to track_path @track
  end

  private

  def track_params
    params.require(:track).permit(:name, :description, :order)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper

  # Find other lessons in the current track
  def find_lessons_in_same_track(track)
    @other_lessons = CodeLesson.where('track_id = ?', track.id)
                     # VideoLesson.where('track_id = ?', track.id) +
                     # Quiz.where('track_id = ?', track.id)
  end

  # Generates order for new lesson in track
  def find_order
    find_lessons_in_same_track Track.find(params[:id])
    @other_lessons.present? ? @other_lessons.map(&:order).max + 1 : 1
  end
end

app/views/tracks/_track_item.html.erb
<% if current_user.has_completed?(item) %>
  <% progress = find_progress_from_item_user(item, current_user) %>
<li class="list-group-item has-completed">
  <div class="tick pull-right">
    <span class="complete-lesson-info" data-toggle="tooltip" data-placement="top" title="<%= time_ago_in_words progress.time_completed %> ago &mdash; <%= progress.number_of_attempts %> attempts">
      <span class="glyphicon glyphicon-ok"></span>
      Completed
    </span>
  </div>
<% else %>
<li class="list-group-item">
<% end %>
  <%= link_to item, class: 'black-icon' do %>
    <span class="octicon octicon-terminal"></span>
    <%= item.name %>
  <% end %>
  <% if !item.visible? && current_user.teacher? %>
    <span class="visible-tooltip visible-tooltip-<%= index %> text-danger" data-placement="top" data-toggle="tooltip" title="You need to add <%= required_empty_fields(item) %>.">
      <span class="octicon octicon-alert"></span>
      This item is not visible to students
    </span>
  <% end %>
  <% if current_user.teacher? %>
    <div class="pull-right code-lesson-options">
      <%= link_to edit_code_lesson_path(item), class: 'black-icon' do %>
        <span class="octicon octicon-pencil"></span>
        Edit
      <% end %>
      <%= link_to code_lesson_stats_path(item), class: 'black-icon' do %>
        <span class="octicon octicon-file-text"></span>
        Show Stats
      <% end %>
    </div>
  <% end %>
</li>

app/views/tracks/edit.html.haml
- provide :title, 'Edit Track'

.container
  .row
    .col-md-6
      %h1 Edit #{@track.name}

      = form_for @track do |f|
        .form-group
          = f.label :name, class: 'control-label'
          = f.text_field :name, class: 'form-control', placeholder: 'Name'
        .form-group
          = f.label :description, class: 'control-label'
          = f.text_area :description, rows: 3, class: 'form-control', placeholder: 'Description'
        .form-group
          = f.submit 'Submit', class: 'btn btn-primary'

app/views/tracks/edit_order.html.haml
- provide :title, 'Edit Order'

.container
  .row
    .col-md-12
      .alert.alert-info.alert-dismissable
        Click and drag the
        %i.fa.fa-align-justify
        icon to rearrage the order of lessons in the track.

    .col-md-8
      %ul#edit-track-sortable.hard-top-10
        - @items.each do |item|
          %li.list-group-item.edit-track-sortable-item{"id" => "#{item.class.name.parameterize}-#{item.id}", "data-id" => "#{item.class.name}-#{item.id}"}

            - # path_for_lesson found in ApplicationHelper
            = link_to item.name, path_for_lesson(item)
            %span.label.label-primary.track-item-label= item.class.name
            %i.fa.fa-align-justify.pull-right.edit-track-move-icon

      - # Whenever the items are re-ordered some JS adds their new values to this form
      = form_for @track, url: update_lesson_order_path, method: :post, html: { class: 'update-lesson-order-form' } do |f|
        = f.hidden_field :track_id, value: @track.id
        - @track.items.each_with_index do |fitem, n|
          %input{"type" => "hidden", "name" => "track[items][#{n}][id]", "id" => "id-#{fitem.class.name}-#{fitem.id}", "value" => fitem.id}
          %input{"type" => "hidden", "name" => "track[items][#{n}][type]", "id" => "type-#{fitem.class.name}-#{fitem.id}", "value" => fitem.class.name}
          %input{"type" => "hidden", "name" => "track[items][#{n}][order]", "id" => "order-#{fitem.class.name}-#{fitem.id}"}
        .pull-right
          = link_to 'Back to Track', track_path(@track), class: "btn btn-default"
          = f.submit 'Submit', class: 'btn btn-primary'

      .update-order-form-status

- # Require sortable files after page load otherwise it doesn't work
= javascript_include_tag 'jquery_sortable'

app/views/tracks/index.html.haml
- provide :title, 'Tracks'

%h1 Tracks#index

app/views/tracks/new.html.haml
- provide :title, 'New Track'

.container
  %h1 New Track

  = form_for @track do |f|
    .form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: 'Name'
    .form-group
      = f.label :description, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :description, rows: 3, class: 'form-control', placeholder: 'Description'
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit 'Submit', class: 'btn btn-default'

app/views/tracks/show.html.haml
- provide :title, @track.name

.container
  = render 'shared/breadcrumbs'

  - if current_user.teacher?
    .pull-right
      = link_to 'Edit Order of Lessons', edit_track_order_path, class: 'btn btn-primary'
      = link_to 'Edit Track', edit_track_path(@track), class: 'btn btn-primary'

      .btn-group
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
          New Lesson
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            = link_to '#', 'data-toggle' => 'modal', 'data-target' => '#new_code_lesson_modal' do
              %span.octicon.octicon-file-code
              New Code Lesson
          %li= link_to 'New Video Lesson', '#'
          %li
            = link_to '#' do
              %span.octicon.octicon-file-text
              New Tutorial

  %h1= @track.name

  %ul.list-group.track-show-items
    - @track.items.each_with_index do |item, index|
      = render 'tracks/track_item', item: item, index: index

- if current_user.teacher?
  = render 'tracks/modal/new_code_lesson_modal'