config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'pages#home'

  # Static Pages
  get '/about',   to: 'pages#about',   as: :about
  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/contact', to: 'pages#contact', as: :contact
  get '/features', to: 'pages#features', as: :features

  get '/dashboard', to: 'dashboards#index', as: :dashboard

  # Organisations
  get '/organisations/new',            to: 'organisations#new',       as: :new_organisation
  get '/organisations/:ref',           to: 'organisations#show',      as: :organisation
  get '/organisations/:ref/edit',      to: 'organisations#edit',      as: :edit_organisation
  get '/organisations',                to: 'organisations#index',     as: :organisations
  match '/organisations',              to: 'organisations#create',    as: :create_organisation, via: :post
  match '/organisations/:ref',         to: 'organisations#destroy',   as: :delete_organisation, via: :delete
  match '/organisations/:ref',         to: 'organisations#update',                              via: :patch

  # Users
  get '/users',          to: 'users#index',   as: :users
  get '/users/:id/edit', to: 'users#edit',    as: :edit_user
  get '/users/:id',      to: 'users#show',    as: :user
  match '/users/:id',    to: 'users#destroy', as: :delete_user, via: :delete
  match '/users/:id',    to: 'users#update',                    via: :patch

  # Student Import
  get '/students/add',      to: 'student_imports#new', as: :add_students
  get '/students/add',      to: 'student_imports#new', as: :student_imports
  get '/students/add',      to: 'student_imports#new', as: :new_student_import
  match '/students/add',    to: 'student_imports#create', via: :post

  match '/students/create', to: 'student_imports#create_student', as: :create_individual_student, via: :post

  # Courses
  resources :courses

  # Tracks
  get '/courses/:id/tracks',     to: 'tracks#index',       as: :tracks
  get '/courses/:id/tracks/new', to: 'tracks#new',         as: :new_track
  get '/tracks/:id',             to: 'tracks#show',        as: :track
  get '/tracks/:id/edit',        to: 'tracks#edit',        as: :edit_track
  get '/tracks/:id/edit-order',  to: 'tracks#edit_order',  as: :edit_track_order
  match '/courses/:id/tracks',   to: 'tracks#create',                 via: :post
  match '/update-lesson-order',  to: 'tracks#update_lesson_order', as: :update_lesson_order, via: :post

  # Code Lessons
  get '/tracks/:id/code-lessons/new',                          to: 'code_lessons#new',       as: :new_code_lesson
  get '/tracks/:id/code-lessons',                              to: 'code_lessons#index',     as: :code_lessons
  get '/code-lessons/:id',                                     to: 'code_lessons#show',      as: :code_lesson
  get '/code-lessons/:id/edit',                                to: 'code_lessons#edit',      as: :edit_code_lesson
  get '/code-lessons/:id/stats',                               to: 'code_lessons#stats',     as: :code_lesson_stats
  get '/code-lessons/:code_lesson_id/submission/:progress_id', to: 'code_lessons#submission', as: :code_lesson_submission
  match '/code-lessons/:id',                                   to: 'code_lessons#destroy',   as: :delete_code_lesson, via: :delete
  match '/code-lessons/:id',                                   to: 'code_lessons#update',                             via: :patch
  match '/tracks/:id/code-lessons',                            to: 'code_lessons#create',    as: :create_code_lesson, via: :post
  match '/evaluate',                                           to: 'code_lessons#evaluate',  as: :new_submission,     via: :post
  match '/run-code',                                           to: 'code_lessons#run_code',  as: :new_run_code,       via: :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organisation
  has_many :progresses

  validates :name,     presence: true, length: { maximum: 50 }
  validates :username, presence: true, uniqueness: { case_sensitive: false,
                                                     scope: :organisation,
                                                     message: 'must be unique' }
  validates :organisation_id, presence: true

  def teacher?
    teacher
  end

  def has_completed?(lesson)
    @progress = Progress.where(lesson_id: lesson.id,
                               lesson_type: lesson.class.name,
                               user_id: id)
    @progress.present? && @progress.first.has_passed
  end

  def progress_in_track(track)
    items = track.items

    completed_items = []
    if items.count == 0
      0
    else
      items.each do |item|
        completed_items.push(item) if self.has_completed?(item)
      end
      (completed_items.count.round(1) / items.count.round(2) * 100).round(0)
    end
  end

  def feed
    Progress.where(user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_teacher!, only: [:index, :destroy, :edit]

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes user_params
      flash[:success] = 'User updated'
      redirect_to users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find params[:id]

    unless current_org == @user.organisation
      redirect_to root_path
      flash[:warning] = 'You cannot access this user.'
    end
  end

  def index
    @users = User.all.where(organisation_id: current_org.id)
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy

    flash[:success] = "User: #{@user.username} deleted"
    redirect_to users_path
  end

  def user_params
    params.require(:user).permit(:name, :email, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # rubocop:disable ColonMethodCall
  # Returns the Gravatar (http://gravatar.com/) for the given user
  def gravatar_for(user, options = { size: 50, circle: false, class: '' })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    class_names = ['gravatar ' + options[:class].to_s]

    options[:circle] ? class_names.push('img-circle') :
                       class_names.push('img-rounded')

    image_tag(url, alt: user.name, class: class_names.join(' '))
  end
end

app/views/users/edit.html.haml
- provide :title, "Edit User #{@user.name}"

.container
  %h1 Edit #{@user.name}

  = form_for @user do |f|
    .form-group
      = f.label :name
      = f.text_field :name, autofocus: true, class: 'form-control'
    .form-group
      = f.label :email
      = f.email_field :email, class: 'form-control'
    .form-group
      = f.label :username
      = f.text_field :username, class: 'form-control'
    .form-group
      = f.submit 'Submit'

app/views/users/index.html.haml
- provide :title, 'All Users'

.container
  .pull-right
    = link_to 'Add More Students', add_students_path, class: 'btn btn-primary'

  %table.table.table-striped.table-hover#users-table
    %thead
      %tr
        %th Name
        %th Email
        %th Username
        %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.username
          %td
            = link_to 'Edit', edit_user_path(user)
            = link_to 'Delete', delete_user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }

app/views/users/show.html.haml
- provide :title, @user.name

.container
  .row
    .col-md-4.user-info
      = gravatar_for @user, size: 400, class: 'user-profile-picture'
      %h1
        = @user.name
        - if @user.teacher?
          %small
            %span.label.label-info TEACHER
      %span.username= @user.username
      %hr
      %ul.user-details
        %li.email
          %span.octicon.octicon-mention
          = @user.email
        %li.join-date
          %span.octicon.octicon-calendar
          Joined on
          = @user.created_at.strftime("%b #{@user.created_at.day.ordinalize}, %Y")

    .col-md-8.user-feed
      %h1 #{@user.name}'s Feed

      %ul.list-group#completed-lessons
        - @user.feed.each do |feed_item|
          %li.list-group-item
            = link_to path_for_lesson(feed_item.lesson) do
              = feed_item.lesson.track.name
              &mdash;
              = feed_item.lesson.name
            .pull-right
              Completed
              = time_ago_in_words feed_item.time_completed
              ago
              %span.glyphicon.glyphicon-ok