config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'pages#home'

  # Static Pages
  get '/about',   to: 'pages#about',   as: :about
  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/contact', to: 'pages#contact', as: :contact
  get '/features', to: 'pages#features', as: :features

  get '/dashboard', to: 'dashboards#index', as: :dashboard

  # Organisations
  get '/organisations/new',            to: 'organisations#new',       as: :new_organisation
  get '/organisations/:ref',           to: 'organisations#show',      as: :organisation
  get '/organisations/:ref/edit',      to: 'organisations#edit',      as: :edit_organisation
  get '/organisations',                to: 'organisations#index',     as: :organisations
  match '/organisations',              to: 'organisations#create',    as: :create_organisation, via: :post
  match '/organisations/:ref',         to: 'organisations#destroy',   as: :delete_organisation, via: :delete
  match '/organisations/:ref',         to: 'organisations#update',                              via: :patch

  # Users
  get '/users',          to: 'users#index',   as: :users
  get '/users/:id/edit', to: 'users#edit',    as: :edit_user
  get '/users/:id',      to: 'users#show',    as: :user
  match '/users/:id',    to: 'users#destroy', as: :delete_user, via: :delete
  match '/users/:id',    to: 'users#update',                    via: :patch

  # Student Import
  get '/students/add',      to: 'student_imports#new', as: :add_students
  get '/students/add',      to: 'student_imports#new', as: :student_imports
  get '/students/add',      to: 'student_imports#new', as: :new_student_import
  match '/students/add',    to: 'student_imports#create', via: :post

  match '/students/create', to: 'student_imports#create_student', as: :create_individual_student, via: :post

  # Courses
  resources :courses

  # Tracks
  get '/courses/:id/tracks',     to: 'tracks#index',       as: :tracks
  get '/courses/:id/tracks/new', to: 'tracks#new',         as: :new_track
  get '/tracks/:id',             to: 'tracks#show',        as: :track
  get '/tracks/:id/edit',        to: 'tracks#edit',        as: :edit_track
  get '/tracks/:id/edit-order',  to: 'tracks#edit_order',  as: :edit_track_order
  match '/courses/:id/tracks',   to: 'tracks#create',                 via: :post
  match '/update-lesson-order',  to: 'tracks#update_lesson_order', as: :update_lesson_order, via: :post

  # Code Lessons
  get '/tracks/:id/code-lessons/new',                          to: 'code_lessons#new',       as: :new_code_lesson
  get '/tracks/:id/code-lessons',                              to: 'code_lessons#index',     as: :code_lessons
  get '/code-lessons/:id',                                     to: 'code_lessons#show',      as: :code_lesson
  get '/code-lessons/:id/edit',                                to: 'code_lessons#edit',      as: :edit_code_lesson
  get '/code-lessons/:id/stats',                               to: 'code_lessons#stats',     as: :code_lesson_stats
  get '/code-lessons/:code_lesson_id/submission/:progress_id', to: 'code_lessons#submission', as: :code_lesson_submission
  match '/code-lessons/:id',                                   to: 'code_lessons#destroy',   as: :delete_code_lesson, via: :delete
  match '/code-lessons/:id',                                   to: 'code_lessons#update',                             via: :patch
  match '/tracks/:id/code-lessons',                            to: 'code_lessons#create',    as: :create_code_lesson, via: :post
  match '/evaluate',                                           to: 'code_lessons#evaluate',  as: :new_submission,     via: :post
  match '/run-code',                                           to: 'code_lessons#run_code',  as: :new_run_code,       via: :post
end

app/models/code_lesson.rb
class CodeLesson < ActiveRecord::Base
  belongs_to :track
  belongs_to :language

  after_validation :make_visible

  validates :name,            presence: true, length: { maximum: 50 }
  validates :lesson_content,  presence: true, on: :update
  validates :instructions,    presence: true, on: :update
  validates :organisation_id, presence: true
  validates :language_id,     presence: true
  validates :user_id,         presence: true
  validates :track_id,        presence: true


  def to_param
    [id, name.parameterize].join('-')
  end

  def visible?
    visible
  end

  def shareable?
    shareable
  end

  def progresses
    Progress.where(lesson_type: self.class.name, lesson_id: id)
  end

  private

    def make_visible
      if name.present? && language_id.present? && lesson_content.present? &&
        instructions.present? && order.present?
        self.visible = true
      end
    end
end

app/controllers/code_lessons_controller.rb
class CodeLessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_teacher!, only: :submission

  layout 'code_lesson', only: [:show, :submission]

  def new
    @code_lesson = CodeLesson.new
  end

  def create
    @track = Track.find params[:id]
    @code_lesson = @track.code_lessons.build(code_lesson_params)
    if @code_lesson.save
      redirect_to edit_code_lesson_path @code_lesson
    else
      flash[:warning] = 'Problem creating Code Lesson'
      redirect_to track_path @track
    end
  end

  def edit
    @code_lesson = CodeLesson.find params[:id]
    @track = @code_lesson.track
    @language = Language.find @code_lesson.language_id
  end

  def update
    @code_lesson = CodeLesson.find params[:id]
    @track = @code_lesson.track
    @language = Language.find @code_lesson.language_id

    if @code_lesson.update_attributes code_lesson_params
      redirect_to code_lesson_path @code_lesson
    else
      render :edit
    end
  end

  def index
    @track = Track.find params[:id]
    redirect_to track_path @track
  end

  def show
    @code_lesson = CodeLesson.find params[:id]
    @track = @code_lesson.track
    @language = Language.find @code_lesson.language_id
    @creator = User.find @code_lesson.user_id
    @progress = Progress.where(lesson_id: @code_lesson.id,
                               lesson_type: 'CodeLesson',
                               user_id: current_user.id)

    code_lesson_info_with_markdown
  end

  def destroy
    @code_lesson = CodeLesson.find params[:id]
    @track = @code_lesson.track

    if @code_lesson.destroy
      flash[:success] = 'Code Lesson deleted'
      redirect_to track_path @track
    else
      flash[:warning] = 'Problem deleting Code Lesson'
      redirect_to track_path @track
    end
  end

  def stats
    @code_lesson = CodeLesson.find params[:id]
    @track = @code_lesson.track

    @progresses = @code_lesson.progresses
  end

  def submission
    @code_lesson = CodeLesson.find params[:code_lesson_id]
    @progress = Progress.find params[:progress_id]
    @language = @code_lesson.language
    @creator = User.find @code_lesson.user_id
    @track = @code_lesson.track
  end

  def run_code
    @cl = CodeLesson.find(params[:lesson_id])

    # Runs user code
    @sandie = Sandie.new(language: Language.find(@cl.language_id).code_eval_slug)
    @code = @sandie.evaluate(code: params[:user_code])

    # Evaluates user code against corectness tests
    @test = evaluate_code_against_tests(params[:user_code],
                                        @code['stdout'],
                                        @cl.correctness_test)

    result = @code[:stderr] == nil && @test[:pass] == "true\n"

    render json: @code.merge({ pass: result }).to_json.inspect
  end

  # The function that code is posted to, to be evaluated
  def evaluate
    @cl = CodeLesson.find(params[:lesson_id])

    # Runs user code
    @sandie = Sandie.new(language: Language.find(@cl.language_id).code_eval_slug)
    @code = @sandie.evaluate(code: params[:user_code])

    # Evaluates user code against corectness tests
    @test = evaluate_code_against_tests(params[:user_code],
                                        @code['stdout'],
                                        @cl.correctness_test)

    result = @code[:stderr] == nil && @test[:pass] == "true\n"

    # Save the code the user has submitted to database
    make_progress(params[:user_id], params[:organisation_id],
                  params[:lesson_id], params[:lesson_type], params[:user_code],
                  result)

    # Returns the result of the evaluation and the result of the correctness tests.
    render json: @code.merge({ pass: result }).to_json.inspect
  end

  def save_progress

  end

  private

  def code_lesson_params
    params.require(:code_lesson).permit(:name, :language_id, :lesson_content,
                                        :starting_code, :instructions, :hints,
                                        :order, :user_id, :organisation_id,
                                        :date_due, :correctness_test)
  end

  def code_lesson_info_with_markdown
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       autolink: true,
                                       space_after_headers: true,
                                       fenced_code_blocks: true,
                                       prettify: true)

    @cl_lesson_content = markdown.render(@code_lesson.lesson_content).html_safe
    @cl_instructions = markdown.render(@code_lesson.instructions).html_safe
    @cl_hints = markdown.render(@code_lesson.hints).html_safe
  end

  def make_progress(user_id, org_id, lesson_id, lesson_type, user_code, result)
    @progress = Progress.where(user_id: user_id,
                               lesson_id: lesson_id,
                               lesson_type: lesson_type,
                               organisation_id: org_id).first_or_create
    if @progress.has_passed
      @progress.update_attributes(content: user_code)
    elsif result
      @progress.update_attributes(content: user_code,
                                  number_of_attempts: @progress.number_of_attempts + 1,
                                  has_passed: result,
                                  time_completed: Time.now)
    else
      @progress.update_attributes(content: user_code,
                                  number_of_attempts: @progress.number_of_attempts + 1,
                                  has_passed: result)
    end
  end

  def evaluate_code_against_tests(user_code, result, tests)
    tests = tests == "" ? true : tests
    {
      pass: Sandie.new(language: 'ruby').evaluate(
        code: <<-EVAL
          code = %Q{#{user_code.to_s}}
          result = %Q{#{result.to_s}}
          puts #{tests}
        EVAL
      )['stdout']
    }
  end
end

app/helpers/code_lessons_helper.rb
module CodeLessonsHelper

  # Returns a human-readable sentence of missing fields needed for the lesson
  # to be public
  def required_empty_fields(code_lesson)
    fields = %w[name language_id lesson_content instructions order]
    missing = []
    fields.each do |field|
      missing.push(field.humanize) if code_lesson.read_attribute(field).blank?
    end

    missing.any? ? missing.to_sentence : 'nothing'
  end
end

app/views/code_lessons/_ace_editor.html.erb
<% if @language.ace_slug == 'html' || @language.ace_slug == 'markdown' %>
  <div id="html_editor"><%= @code_lesson.starting_code %></div>
  <div id="html_container">
    <iframe id="html_view">The iframe was unable to load.</iframe>
  </div>
<% else %>
  <% if on_page 'code_lessons', 'submission' %>
    <div id="editor"><%= @progress.content %></div>
  <% else %>
    <% if params[:defaultcode] == 'true' %>
      <div id="editor"><%= @code_lesson.starting_code %></div>
    <% elsif @progress.length > 0 %>
      <div id="editor"><%= @progress.first.content %></div>
    <% else %>
      <div id="editor"><%= @code_lesson.starting_code %></div>
    <% end %>
    <div id="success_bar" style="display:none;">
      <div class="pull-right">
        <%= link_to_next_lesson @code_lesson %>
      </div>
      <div class="success-text">
        Well Done! You passed the lesson, click the button to move on...
      </div>
    </div>
  <% end %>
  <div id="console"></div>
<% end %>

app/views/code_lessons/_ace_javascript.erb
<% if on_page('code_lessons', 'show') || on_page('code_lessons', 'submission') %>
  <script>
    <% if @language.ace_slug == 'html' || @language.ace_slug == 'markdown' %>
      var editor_id = 'html_editor';
    <% else %>
      var editor_id = 'editor';
    <% end %>

    var editor = ace.edit(editor_id);
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/<%= escape_javascript(@language.ace_slug) %>");
    document.getElementById(editor_id).style.fontSize='14px';
    editor.getSession().setTabSize(2);
    editor.getSession().setUseWrapMode(true);
    editor.getSession().setWrapLimitRange();

    editor.getSession().on('change', function() {
      $('#user-code').val(editor.getValue());
    });

    var jqconsole = $('#console').jqconsole('', '');

    var startPrompt = function () {
      jqconsole.Prompt(true, function (input) {
        jqconsole.Write(input + '\n', 'jqconsole-output');
        // Scrolls to bottom when content goes of page
        $(".jqconsole").animate({
          scrollTop: $(".jqconsole").height()
        }, 1000);
        startPrompt();
      });
    };
    startPrompt();
  </script>
<% elsif on_page('code_lessons', 'edit') || on_page('code_lessons', 'update') %>
  <script>
    var editor1ID = "default-code-editor",
        editor2ID = "correctness-test-editor";

    var editor1 = ace.edit(editor1ID);
    editor1.setTheme("ace/theme/monokai");
    editor1.getSession().setMode("ace/mode/<%= escape_javascript(@language.ace_slug) %>");
    document.getElementById(editor1ID).style.fontSize='14px';
    editor1.getSession().setTabSize(2);
    editor1.getSession().setUseWrapMode(true);
    editor1.getSession().setWrapLimitRange();

    var editor2 = ace.edit(editor2ID);
    editor2.setTheme("ace/theme/monokai");
    editor2.getSession().setMode("ace/mode/<%= escape_javascript(@language.ace_slug) %>");
    document.getElementById(editor2ID).style.fontSize='14px';
    editor2.getSession().setTabSize(2);
    editor2.getSession().setUseWrapMode(true);
    editor2.getSession().setWrapLimitRange();

    var textarea = $('#code_lesson_starting_code').hide();
    editor1.getSession().setValue(textarea.val());
    editor1.getSession().on('change', function(){
      textarea.val(editor1.getValue());
    });

    var textarea2 = $('#code_lesson_correctness_test').hide();
    editor2.getSession().setValue(textarea2.val());
    editor2.getSession().on('change', function(){
      textarea2.val(editor2.getValue());
    });
  </script>
<% end %>

<% if @language.ace_slug == 'html' %>
  <script>
  var typingTimer;
  var doneTypingInterval = 5000; // Time in ms after user stops typing waited
                                 // until contents of editor are put into iframe.
  var myiframe = $('#html_view'),
      setFontScript = "<style>body{font-family:Helvetica, Arial, sans-serif;}</style>";

  myiframe.attr("src", "data:text/html;charset=utf-8," + setFontScript + escape(editor.getValue()));

  function addContentsToIframe() {
    myiframe.attr("src", "data:text/html;charset=utf-8," + setFontScript + escape(editor.getValue()));
  }

  editor.getSession().on('change', function(e) {
    clearTimeout(typingTimer);
    typingTimer = setTimeout(addContentsToIframe(), doneTypingInterval);
  });

  </script>
<% elsif @language.ace_slug == 'markdown' %>
  <script>
  var myiframe = $('#html_view'),
      startingContent = marked(editor.getValue()),
      setFontScript = "<style>body{font-family:Helvetica, Arial, sans-serif;}</style>";
      myiframe.attr("src", "data:text/html;charset=utf-8," + setFontScript + startingContent);

  editor.getSession().on('change', function(e) {
    var newContent = marked(editor.getValue());
    myiframe.attr("src", "data:text/html;charset=utf-8," + setFontScript + newContent);
  });
  </script>
<% end %>

app/views/code_lessons/_submit_code_form.html.erb
<% if @code_lesson.language.ace_slug == 'javascript' %>
  <%= link_to '#', class: 'btn btn-success btn-lg run-code-button', id: 'javascript-run-code-buttom' do %>
    Run Code
    <i class="fa fa-play-circle"></i>
  <% end %>
<% else %>
  <% if on_page('code_lesson', 'show') %>
    <%= link_to '#', class: 'btn btn-success btn-lg run-code-button', id: 'default-run-code-buttom', data: {
            submit_url: new_submission_path,
            lesson_id: @code_lesson.id,
            user_id: current_user.id,
            item_type: @code_lesson.class.name,
            track_id: @code_lesson.track.id,
            organisation_id: current_org.id } do %>
      Run Code
      <i class="fa fa-play-circle"></i>
    <% end %>
  <% else %>
    <%= link_to '#', class: 'btn btn-success btn-lg run-code-button', id: 'default-run-code-sandbox-buttom', data: {
            submit_url: new_run_code_path,
            lesson_id: @code_lesson.id } do %>
      Run Code
      <i class="fa fa-play-circle"></i>
    <% end %>
  <% end %>

  <input type="hidden" value="" id="user-code">
<% end %>

app/views/code_lessons/edit.html.haml
- provide :title, "Edit #{@code_lesson.name}"

.container
  = render 'shared/breadcrumbs'

  %h1= @code_lesson.name

  .col-lg-8
    %ul.nav.nav-tabs
      %li.active= link_to 'Starting Code', '#starting_code', 'data-toggle' => 'tab'
      %li= link_to 'Correctness Test', '#correctness_test', 'data-toggle' => 'tab'

  = form_for @code_lesson do |f|
    .tab-content
      #starting_code.tab-pane.active
        .col-lg-8
          .form-group.edit-cl-editor-form-group
            = f.text_area :starting_code, class: 'form-control', style: 'display:none;'
            #default-code-editor.form-control
      #correctness_test.tab-pane
        .col-lg-8
          .form-group.edit-cl-editor-form-group
            = f.text_area :correctness_test, class: 'form-control', style: 'display:none;'
            %p
              The
              %code code
              variable contains the code the user submitted, to check if it contains code use the following syntax:
              %pre code.include?('console.log')
            %p
              The
              %code result
              variable contains the code the user submitted, to check if it contains code use the following syntax:
              %pre result.include?('Hello, World')
            %p
              The correctnes tests are written in Ruby, so the following would be acceptable to do a non-case-sensitive check:
              %pre result.downcase.include?('hello, world')
            #correctness-test-editor.form-control
    .col-lg-4
      = render 'shared/error_messages', object: f.object

      .form-group
        = f.label :name
        %span.required
          %em (required)
        = f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control"

      .form-group
        = f.label :language_id, 'Language'
        %span.required
          %em (required)
        = f.collection_select :language_id, Language.all, :id, :name, { prompt: true }, { class: "form-control" }

      .form-group
        - if @code_lesson.date_due.present?
          %input#disable_date{checked: 'checked', type: 'checkbox'}
          %label{for: 'disable_date'} Is this due for a certain date?
          %br/
          %br/
          = f.label :date_due, 'Date Due'
          = f.date_field :date_due, placeholder: "Date Due", class: "form-control"
        - else
          %input#disable_date{type: 'checkbox'}
          %label{for: 'disable_date'} Is this due for a certain date?
          %br/
          %br/
          = f.label :date_due, 'Date Due'
          = f.date_field :date_due, placeholder: 'Date Due', class: 'form-control', disabled: 'disabled'

      .form-group
        .alert.alert-info
          %p
            Lesson Content, Instructions and Hints are all written in
            %strong Markdown.
            = link_to 'Learn how to use it.', '#', 'data-toggle' => 'modal', 'data-target' => '#learn_markdown'

      .form-group
        = f.label :lesson_content, 'Lesson Content'
        %span.required
          %em (required)
        = f.text_area :lesson_content, placeholder: "Lesson Content", rows: 6, class: "form-control"

      .form-group
        = f.label :instructions
        %span.required
          %em (required)
        = f.text_area :instructions, placeholder: "Instructions", rows: 6, class: "form-control"

      .form-group
        = f.label :hints
        = f.text_area :hints, placeholder: "Hints", rows: 6, class: "form-control"

      = f.hidden_field :user_id, value: current_user.id

      .form-group.pull-right
        = link_to "Back to Lesson", code_lesson_path(@code_lesson), class: "btn btn-default"
        = f.submit "Submit", class: "btn btn-primary"

= render 'code_lessons/ace_javascript'
= render 'code_lessons/markdown_modal'

app/views/code_lessons/index.html.haml
- provide :title, 'Code Lessons'

app/views/code_lessons/new.html.haml
%h1 CodeLessons#new

app/views/code_lessons/show.html.erb
<% provide :title, @code_lesson.name %>

<%= render 'code_lessons/ace_editor' %>

<div id="code_lesson_sidebar">
  <% unless @code_lesson.visible? %>
    <div class="container hidden-lesson-container">
      <span class="mega-octicon octicon-lock hidden-icon"></span>
      <span class="visible-tooltip label label-hidden" data-placement="right" data-toggle="tooltip" title="You need to add <%= required_empty_fields(@code_lesson) %> to make this lesson visible.">
        Hidden Lesson
      </span>
    </div>
  <% end %>
  <div class="container">
    <% if params[:defaultcode] == 'true' %>
      <%= link_to 'Reset to Your Saved Code', request.path, class: 'btn btn-primary' %>
    <% elsif @progress.count > 0 && @progress.first.content != @code_lesson.starting_code %>
      <%= link_to 'Reset to Default Lesson Code', "#{request.original_url}?defaultcode=true", class: 'btn btn-primary' %>
    <% end %>
    <h1>
      <%= @code_lesson.name %>
    </h1>
    <p>
<% # These must be indented like this and in ERB to remove formatting errors %>
<%= @cl_lesson_content %>
    </p>
  </div>
  <div class="container">
    <h3>Instructions</h3>
    <p>
<% # These must be indented like this and in ERB to remove formatting errors %>
<%= @cl_instructions %>
    </p>
  </div>
  <% if @code_lesson.hints.present? %>
    <div class="container">
      <h3>Hints</h3>
      <p>
<% # These must be indented like this and in ERB to remove formatting errors %>
<%= @cl_hints %>
      </p>
    </div>
  <% end %>
  <% if current_user.teacher? %>
    <div class="container">
      Lesson Created by:
      <%= link_to @creator.name, @creator %>
    </div>
    <div class="container option-buttons-container">
      <%= link_to 'Edit Lesson', edit_code_lesson_path(@code_lesson), class: 'btn btn-block btn-primary' %>
      <%= link_to code_lesson_stats_path(@code_lesson), class: 'btn btn-block btn-primary' do %>
        <span class="octicon octicon-organization"></span>
        Show Lessons Statistics
      <% end %>
    </div>
  <% end %>
</div>
<div id="code_lesson_submit_container">
  <div class="center">
    <%= render 'code_lessons/submit_code_form' %>
  </div>
</div>

app/views/code_lessons/stats.html.haml
- provide :title, "#{@code_lesson.name} - Statistics"

.container
  = render 'shared/breadcrumbs'

  %h1
    = @code_lesson.name
    %small Statistics

  %table.table
    %thead
      %tr
        %th User
        %th Attempts to Complete
        %th Time of Completion
        %th View Code
    %tbody
      - if @progresses.any?
        - @progresses.each do |progress|
          %tr
            %td= link_to "#{progress.user.name} (#{progress.user.username})", user_path(progress.user)
            %td= progress.number_of_attempts
            %td
              = progress.time_completed.strftime("%a %b #{progress.time_completed.day.ordinalize}, %Y - %H:%M")
              &mdash;
              %strong
                = surround "(", ")" do
                  = time_ago_in_words progress.time_completed
                  ago
            %td= link_to 'View Code', code_lesson_submission_path(@code_lesson, progress)
      - else
        %tr
          %td{"colspan" => 4, "style" => 'text-align:center;'}
            Nobody has completed this lesson.

app/views/code_lessons/submission.html.erb
<% provide :title, "#{@progress.user.name}'s Submission - #{@code_lesson.name}" %>

<%= render 'code_lessons/ace_editor' %>

<div id="code_lesson_sidebar">
  <div class="container">
    <div class="alert alert-success submission-info" role="alert">
      <div class="fact">
        Viewing Submission for:<br>
        <span class="alert-link">
          <%= link_to @progress.user.name, @progress.user %>
        </span>
      </div>

      <div class="fact">
        Attempts Needed to Complete:<br>
        <span class="alert-link">
          <%= @progress.number_of_attempts %>
        </span>
      </div>

      <div class="fact">
        Time of Completion:<br>
        <span class="alert-link">
          <%= @progress.time_completed.strftime("%b #{@progress.time_completed.day.ordinalize}, %Y - %H:%M") %>
          <br>
          (<%= time_ago_in_words @progress.time_completed %> ago)
        </span>
      </div>
    </div>
  </div>
  <div class="container">
    <h1>
      <%= @code_lesson.name %>
    </h1>
    <p>
<% # These must be written like this and in ERB to remove formatting errors %>
<%= @cl_lesson_content %>
    </p>
  </div>
  <div class="container">
    <h3>Instructions</h3>
    <p>
<% # These must be written like this and in ERB to remove formatting errors %>
<%= @cl_instructions %>
    </p>
  </div>
  <% if @code_lesson.hints.present? %>
    <div class="container">
      <h3>Hints</h3>
      <p>
<% # These must be written like this and in ERB to remove formatting errors %>
<%= @cl_hints %>
      </p>
    </div>
  <% end %>
  <% if current_user.teacher? %>
    <div class="container">
      Lesson Created by:
      <%= link_to @creator.name, @creator %>
    </div>
    <div class="container">
      <%= link_to code_lesson_path(@code_lesson), class: 'btn btn-primary' do %>
        <span class="octicon octicon-organization"></span>
        Show Original Lesson
      <% end %>
    </div>
  <% end %>
</div>
<div id="code_lesson_submit_container">
  <div class="center">
    <%= render 'code_lessons/submit_code_form' %>
  </div>
</div>