config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'pages#home'

  # Static Pages
  get '/about',   to: 'pages#about',   as: :about
  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/contact', to: 'pages#contact', as: :contact
  get '/features', to: 'pages#features', as: :features

  get '/dashboard', to: 'dashboards#index', as: :dashboard

  # Organisations
  get '/organisations/new',            to: 'organisations#new',       as: :new_organisation
  get '/organisations/:ref',           to: 'organisations#show',      as: :organisation
  get '/organisations/:ref/edit',      to: 'organisations#edit',      as: :edit_organisation
  get '/organisations',                to: 'organisations#index',     as: :organisations
  match '/organisations',              to: 'organisations#create',    as: :create_organisation, via: :post
  match '/organisations/:ref',         to: 'organisations#destroy',   as: :delete_organisation, via: :delete
  match '/organisations/:ref',         to: 'organisations#update',                              via: :patch

  # Users
  get '/users',          to: 'users#index',   as: :users
  get '/users/:id/edit', to: 'users#edit',    as: :edit_user
  get '/users/:id',      to: 'users#show',    as: :user
  match '/users/:id',    to: 'users#destroy', as: :delete_user, via: :delete
  match '/users/:id',    to: 'users#update',                    via: :patch

  # Student Import
  get '/students/add',      to: 'student_imports#new', as: :add_students
  get '/students/add',      to: 'student_imports#new', as: :student_imports
  get '/students/add',      to: 'student_imports#new', as: :new_student_import
  match '/students/add',    to: 'student_imports#create', via: :post

  match '/students/create', to: 'student_imports#create_student', as: :create_individual_student, via: :post

  # Courses
  resources :courses

  # Tracks
  get '/courses/:id/tracks',     to: 'tracks#index',       as: :tracks
  get '/courses/:id/tracks/new', to: 'tracks#new',         as: :new_track
  get '/tracks/:id',             to: 'tracks#show',        as: :track
  get '/tracks/:id/edit',        to: 'tracks#edit',        as: :edit_track
  get '/tracks/:id/edit-order',  to: 'tracks#edit_order',  as: :edit_track_order
  match '/courses/:id/tracks',   to: 'tracks#create',                 via: :post
  match '/update-lesson-order',  to: 'tracks#update_lesson_order', as: :update_lesson_order, via: :post

  # Code Lessons
  get '/tracks/:id/code-lessons/new',                          to: 'code_lessons#new',       as: :new_code_lesson
  get '/tracks/:id/code-lessons',                              to: 'code_lessons#index',     as: :code_lessons
  get '/code-lessons/:id',                                     to: 'code_lessons#show',      as: :code_lesson
  get '/code-lessons/:id/edit',                                to: 'code_lessons#edit',      as: :edit_code_lesson
  get '/code-lessons/:id/stats',                               to: 'code_lessons#stats',     as: :code_lesson_stats
  get '/code-lessons/:code_lesson_id/submission/:progress_id', to: 'code_lessons#submission', as: :code_lesson_submission
  match '/code-lessons/:id',                                   to: 'code_lessons#destroy',   as: :delete_code_lesson, via: :delete
  match '/code-lessons/:id',                                   to: 'code_lessons#update',                             via: :patch
  match '/tracks/:id/code-lessons',                            to: 'code_lessons#create',    as: :create_code_lesson, via: :post
  match '/evaluate',                                           to: 'code_lessons#evaluate',  as: :new_submission,     via: :post
  match '/run-code',                                           to: 'code_lessons#run_code',  as: :new_run_code,       via: :post
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_student_dashboard.html.haml
#info
  .container
    .row
      .col-md-12
        %h1
          = current_org.name
          Dashboard
    .row.stats
      .col-sm-4
        - students = pluralise(current_org.users.count, 'user')
        %strong= students.first
        = students.last
      .col-sm-4
        - courses = pluralise(current_org.courses.count, 'course')
        %strong= courses.first
        = courses.last
      .col-sm-4
        %strong #{'3'}
        homework overdue

app/views/dashboards/_teacher_dashboard.html.haml
#info
  .container
    .row
      .col-md-12
        - if current_org.users.count < (current_org.max_users * 0.1).to_i
          .alert.alert-info.alert-dismissible{role: "alert"}
            %button.close{type: "button", "data-dismiss" => "alert"}
              %span{"aria-hidden" => "true"} &times;
              %span.sr-only Close
            You don't seem to have many users,
            = link_to 'click here to add users.', add_students_path, class: 'alert-link'
        %h1 #{current_org.name} Dashboard
    .row.stats
      .col-sm-4
        - users = pluralise(current_org.users.count, 'user')
        = link_to users_path do
          %strong= users.first
          = users.last
          in your organisation
      .col-sm-4
        - courses = pluralise(current_org.courses.count, 'course')
        = link_to courses_path do
          %strong= courses.first
          = courses.last
      .col-sm-4
        %strong #{'3'}
        homework overdue

app/views/dashboards/index.html.haml
- provide :title, 'Dashboard'

- if current_user.teacher?
  = render 'dashboards/teacher_dashboard'
- else
  = render 'dashboards/student_dashboard'